spring.application.name=swe-project

# ---- SQLite (dev) ----
spring.datasource.url=jdbc:sqlite:./data/foodwaste.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# SQL init (seed admin etc.)
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=3080
server.error.include-message=always

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO

# File uploads
app.upload-dir=./uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
